from django.urls import path

from accounts.views import (
    ForgotPasswordView,
    InviteAcceptView,
    InviteListCreateView,
    InvitePreviewView,
    LoginView,
    LogoutView,
    MeView,
    RefreshView,
    ResetPasswordView,
    SignupView,
    AccessView,
    DashboardStatsView,
    UserDeactivateView,
    UserReactivateView,
    UserToggleAdminView,
    UserToggleDoctorView,
    VerifyEmailView,
    WebSocketTicketView,
    MyClinicsView,
)

urlpatterns = [
    path("signup/", SignupView.as_view(), name="signup"),
    path("verify-email/", VerifyEmailView.as_view(), name="verify-email"),
    path("forgot-password/", ForgotPasswordView.as_view(), name="forgot-password"),
    path("reset-password/", ResetPasswordView.as_view(), name="reset-password"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("refresh/", RefreshView.as_view(), name="refresh"),
    path("me/", MeView.as_view(), name="me"),
    path("my-clinics/", MyClinicsView.as_view(), name="my-clinics"),
    path("access/", AccessView.as_view(), name="access"),
    path("dashboard/", DashboardStatsView.as_view(), name="dashboard"),
    path("users/<int:user_id>/deactivate/", UserDeactivateView.as_view(), name="user-deactivate"),
    path("users/<int:user_id>/reactivate/", UserReactivateView.as_view(), name="user-reactivate"),
    path("users/<int:user_id>/toggle-admin/", UserToggleAdminView.as_view(), name="user-toggle-admin"),
    path("users/<int:user_id>/toggle-doctor/", UserToggleDoctorView.as_view(), name="user-toggle-doctor"),
    path("ws-ticket/", WebSocketTicketView.as_view(), name="ws-ticket"),
    path("invites/", InviteListCreateView.as_view(), name="invite-list-create"),
    path("invites/preview/<str:token>/", InvitePreviewView.as_view(), name="invite-preview"),
    path("invites/accept/<str:token>/", InviteAcceptView.as_view(), name="invite-accept"),
]
