# Generated by Django 5.0.6 on 2026-09-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("followups", "0002_alter_followup_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followup",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("scheduled", "Scheduled"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
