# Generated by Django 5.0.6 on 2026-07-31 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ai_enabled", models.BooleanField(default=True)),
                ("ai_default_language", models.CharField(default="en", max_length=32)),
                ("ai_voice_enabled", models.BooleanField(default=True)),
                ("ai_transcription_enabled", models.BooleanField(default=True)),
                (
                    "default_consultation_minutes",
                    models.PositiveSmallIntegerField(default=15),
                ),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("working_hours_start", models.TimeField(default="09:00")),
                ("working_hours_end", models.TimeField(default="17:00")),
                ("sms_enabled", models.BooleanField(default=True)),
                ("email_enabled", models.BooleanField(default=True)),
                ("whatsapp_enabled", models.BooleanField(default=False)),
                ("auto_generate_tokens", models.BooleanField(default=True)),
                ("token_prefix", models.CharField(default="", max_length=10)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="changed_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clinic",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuration",
                        to="clinics.clinic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinic Configuration",
                "verbose_name_plural": "Clinic Configurations",
            },
        ),
    ]
