# Generated by Django 5.0.6 on 2026-09-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0002_clinicconfiguration"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="clinic",
            name="clinic_type",
            field=models.CharField(
                choices=[
                    ("single_doctor", "Single Doctor"),
                    ("multi_doctor", "Multi Doctor"),
                ],
                default="multi_doctor",
                max_length=32,
            ),
        ),
    ]
