# Generated by Django 5.0.6 on 2026-09-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0003_clinic_address_clinic_clinic_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="clinic",
            name="facilities",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="clinic",
            name="holiday_calendar",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="clinic",
            name="phone",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="clinic",
            name="registration_number",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="clinic",
            name="support_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="clinic",
            name="tax_id",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="clinic",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
