# Generated by Django 5.0.6 on 2026-09-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0006_paymenttransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="is_onboarded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="clinicconfiguration",
            name="ai_phone_number",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="clinicconfiguration",
            name="ai_voice_type",
            field=models.CharField(default="basic", max_length=50),
        ),
    ]
