# Generated by Django 5.0.6 on 2026-09-25 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0007_clinic_is_onboarded_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="branches",
                to="clinics.clinic",
            ),
        ),
        migrations.CreateModel(
            name="ClinicPhoneNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number",
                    models.CharField(
                        help_text="Digits only, with country code, e.g. 918031805277.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("provider", models.CharField(default="plivo", max_length=20)),
                ("country_iso", models.CharField(default="IN", max_length=2)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("monthly_rental_rate", models.CharField(blank=True, max_length=20)),
                ("app_id", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending approval"),
                            ("purchased", "Purchased"),
                            ("active", "Active"),
                        ],
                        default="purchased",
                        max_length=20,
                    ),
                ),
                ("last_error", models.TextField(blank=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="changed_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clinic",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_number",
                        to="clinics.clinic",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
