# Generated by Django 5.0.6 on 2026-09-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0009_link_existing_branches"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicphonenumber",
            name="bought_here",
            field=models.BooleanField(default=True),
        ),
    ]
