# Generated by Django 5.0.6 on 2026-07-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_passwordresettoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="membership_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("invited", "Invited"),
                    ("suspended", "Suspended"),
                    ("archived", "Archived"),
                ],
                default="active",
                max_length=32,
            ),
        ),
    ]
