# Generated by Django 5.0.6 on 2026-08-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_membership_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_clinic_admin",
            field=models.BooleanField(default=False),
        ),
    ]
