# Generated by Django 5.0.6 on 2026-08-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_is_clinic_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_doctor",
            field=models.BooleanField(default=False),
        ),
    ]
