# Generated by Django 5.0.6 on 2026-09-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_age_user_gender"),
        ("clinics", "0007_clinic_is_onboarded_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="clinics",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="clinics.clinic"
            ),
        ),
    ]
