# Generated by Django 5.0.6 on 2026-08-02 09:15

import django.db.models.deletion
import reports.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinics", "0002_clinicconfiguration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("patient_summary", "Patient Summary"),
                            ("appointment_analytics", "Appointment Analytics"),
                            ("clinical_encounters", "Clinical Encounters"),
                            ("follow_up_status", "Follow-up Status"),
                            ("queue_performance", "Queue Performance"),
                            ("revenue_report", "Revenue Report"),
                            ("custom", "Custom Report"),
                        ],
                        default="custom",
                        max_length=30,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("csv", "CSV"),
                            ("excel", "Excel"),
                            ("text", "Plain Text"),
                        ],
                        default="pdf",
                        max_length=10,
                    ),
                ),
                ("allowed_roles", models.JSONField(blank=True, default=list)),
                (
                    "configuration",
                    models.JSONField(
                        default=dict,
                        help_text="JSON configuration for report generation (filters, columns, grouping, etc.)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_scheduled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this report should be generated automatically on a schedule",
                    ),
                ),
                (
                    "schedule_cron",
                    models.CharField(
                        blank=True,
                        help_text="Cron expression for scheduled reports (e.g., '0 9 * * MON')",
                        max_length=100,
                    ),
                ),
                (
                    "retention_days",
                    models.PositiveSmallIntegerField(
                        default=7,
                        help_text="How long report files and links remain available.",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="changed_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clinics.clinic"
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Template",
                "verbose_name_plural": "Report Templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReportExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parameters",
                    models.JSONField(
                        default=dict,
                        help_text="Parameters used for this specific report execution",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "result_file",
                    models.FileField(
                        blank=True,
                        help_text="Generated report file",
                        null=True,
                        upload_to=reports.models.report_file_path,
                        validators=[reports.models.validate_file_extension],
                    ),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="Size of the generated file in bytes",
                        null=True,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When this report file should be deleted"
                    ),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this report has been downloaded",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the async task (e.g., Celery task ID)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="changed_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clinics.clinic"
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="reports.reporttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Execution",
                "verbose_name_plural": "Report Executions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportAccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[("download", "Download")],
                        default="download",
                        max_length=32,
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="changed_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clinics.clinic"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_access_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_tokens",
                        to="reports.reportexecution",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["clinic", "execution", "purpose"],
                        name="reports_rep_clinic__6226a5_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="reports_rep_expires_7a32ea_idx"
                    ),
                ],
            },
        ),
    ]
