# Generated by Django 5.0.6 on 2026-07-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("login_success", "Login Success"),
                    ("login_failure", "Login Failure"),
                    ("password_reset", "Password Reset"),
                    ("signup", "Signup"),
                    ("invite_created", "Invite Created"),
                    ("invite_accepted", "Invite Accepted"),
                    ("role_changed", "Role Changed"),
                    ("user_deactivated", "User Deactivated"),
                    ("user_reactivated", "User Reactivated"),
                    ("data_exported", "Data Exported"),
                ],
                max_length=64,
            ),
        ),
    ]
