# Generated by Django 5.0.6 on 2026-07-31 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_alter_authevent_event_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="authevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("login_success", "Login Success"),
                    ("login_failure", "Login Failure"),
                    ("logout", "Logout"),
                    ("password_reset", "Password Reset"),
                    ("signup", "Signup"),
                    ("invite_created", "Invite Created"),
                    ("invite_accepted", "Invite Accepted"),
                    ("role_changed", "Role Changed"),
                    ("user_deactivated", "User Deactivated"),
                    ("user_reactivated", "User Reactivated"),
                    ("data_exported", "Data Exported"),
                ],
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="DeviceSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=64, unique=True)),
                ("user_agent", models.TextField()),
                ("ip_address", models.GenericIPAddressField()),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen"],
            },
        ),
    ]
