# Generated by Django 5.0.6 on 2026-08-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0004_datachangeevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datachangeevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("read", "Read"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("deactivate", "Deactivate"),
                    ("reactivate", "Reactivate"),
                ],
                max_length=20,
            ),
        ),
    ]
