# Generated by Django 5.0.6 on 2026-07-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
