# Generated by Django 5.0.6 on 2026-08-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_appointment_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("checked_in", "Checked in"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("no_show", "No show"),
                    ("needs_reschedule", "Needs Reschedule"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
    ]
