# Generated by Django 5.0.6 on 2026-08-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0005_alter_appointment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="priority",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("urgent", "Urgent"),
                    ("emergency", "Emergency"),
                ],
                default="normal",
                max_length=16,
            ),
        ),
    ]
