# Generated by Django 5.0.6 on 2026-09-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0006_appointment_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="reminder_24h_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appointment",
            name="reminder_2h_sent",
            field=models.BooleanField(default=False),
        ),
    ]
