# Generated by Django 5.0.6 on 2026-07-31 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("growth", "Growth"),
                            ("enterprise", "Enterprise"),
                        ],
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("max_admins", models.PositiveIntegerField(default=1)),
                ("max_receptionists", models.PositiveIntegerField(default=2)),
                ("max_doctors", models.PositiveIntegerField(default=3)),
                ("feature_flags", models.JSONField(blank=True, default=dict)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="changed_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClinicEntitlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "max_admins_override",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "max_receptionists_override",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "max_doctors_override",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("feature_flags_override", models.JSONField(blank=True, default=dict)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="changed_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clinic",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entitlement",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clinic_entitlements",
                        to="subscriptions.subscriptionplan",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
