# Generated by Django 5.0.6 on 2026-07-30 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0003_initial"),
        ("clinics", "0001_initial"),
        ("doctors", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QueueToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("service_date", models.DateField(db_index=True)),
                ("token_number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("serving", "Serving"),
                            ("seen", "Seen"),
                            ("skipped", "Skipped"),
                        ],
                        default="waiting",
                        max_length=16,
                    ),
                ),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("served_at", models.DateTimeField(blank=True, null=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="queue_token",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="changed_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clinics.clinic"
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="queue_tokens",
                        to="doctors.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="queue_tokens",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["service_date", "token_number"],
            },
        ),
        migrations.AddConstraint(
            model_name="queuetoken",
            constraint=models.UniqueConstraint(
                fields=("clinic", "doctor", "service_date", "token_number"),
                name="uniq_daily_doctor_token",
            ),
        ),
    ]
