# Generated by Django 5.0.6 on 2026-08-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queue_mgmt", "0002_queuetoken_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queuetoken",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting"),
                    ("checked_in", "Checked In"),
                    ("called", "Called"),
                    ("in_consultation", "In Consultation"),
                    ("completed", "Completed"),
                    ("skipped", "Skipped"),
                ],
                default="waiting",
                max_length=16,
            ),
        ),
    ]
