# Generated by Django 5.0.6 on 2026-08-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queue_mgmt", "0003_alter_queuetoken_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="queuetoken",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="queuetoken",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting"),
                    ("checked_in", "Checked In"),
                    ("called", "Called"),
                    ("in_consultation", "In Consultation"),
                    ("completed", "Completed"),
                    ("skipped", "Skipped"),
                ],
                default="waiting",
                max_length=20,
            ),
        ),
    ]
