# Generated by Django 5.0.6 on 2026-07-30 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai_agent", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="calllog",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="call_logs",
                to="patients.patient",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentconfiguration",
            constraint=models.UniqueConstraint(
                fields=("clinic", "purpose", "language"),
                name="uniq_agent_purpose_language",
            ),
        ),
    ]
