# Generated by Django 5.0.6 on 2026-09-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_agent", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="calllog",
            name="recording_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="calllog",
            name="summary",
            field=models.TextField(blank=True),
        ),
    ]
