# Generated by Django 5.0.6 on 2026-09-24 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_agent", "0003_calllog_recording_url_calllog_summary"),
        ("clinics", "0007_clinic_is_onboarded_and_more"),
        ("patients", "0008_alter_messagelog_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="calllog",
            name="external_call_id",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name="calllog",
            name="recording_file",
            field=models.FileField(blank=True, upload_to="call_recordings/%Y/%m/"),
        ),
        migrations.AlterField(
            model_name="calllog",
            name="recording_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddConstraint(
            model_name="calllog",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_call_id", ""), _negated=True),
                fields=("clinic", "external_call_id"),
                name="uniq_calllog_external_call",
            ),
        ),
    ]
