# Generated by Django 5.0.6 on 2026-10-01 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0004_calllog_external_id_recording_file'),
        ('clinics', '0010_phone_number_bought_here'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceAgentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_message', models.TextField(blank=True)),
                ('system_prompt', models.TextField(blank=True)),
                ('model_type', models.CharField(choices=[('standard', 'Standard'), ('realtime', 'Realtime')], default='standard', max_length=16)),
                ('stt', models.JSONField(blank=True, default=dict)),
                ('llm', models.JSONField(blank=True, default=dict)),
                ('tts', models.JSONField(blank=True, default=dict)),
                ('realtime', models.JSONField(blank=True, default=dict)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_agent', to='clinics.clinic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
