# Generated by Django 5.0.6 on 2026-08-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_messagelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="medical_history",
            field=models.TextField(blank=True),
        ),
    ]
