# Generated by Django 5.0.6 on 2026-08-06 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_patient_medical_history"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="medical_history",
        ),
    ]
