# Generated by Django 5.0.6 on 2026-08-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_remove_patient_medical_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="patient",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
