# Generated by Django 5.0.6 on 2026-09-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "patients",
            "0005_patient_blood_group_patient_emergency_contact_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="messagelog",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="messagelog",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("delivered", "Delivered"),
                    ("read", "Read"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="messagelog",
            name="is_sent",
            field=models.BooleanField(default=False),
        ),
    ]
