# Generated by Django 5.0.6 on 2026-09-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0006_messagelog_metadata_messagelog_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagelog",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("sent", "Sent"),
                    ("delivered", "Delivered"),
                    ("read", "Read"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
