# Generated by Django 5.0.6 on 2026-07-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="specialty",
            field=models.CharField(default="General Practice", max_length=120),
        ),
    ]
