# Generated by Django 5.0.6 on 2026-08-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0002_alter_doctor_specialty"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="available_from",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="available_to",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="max_patients_per_day",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
