# Generated by Django 5.0.6 on 2026-08-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0003_doctor_available_from_doctor_available_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="lunch_from",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="lunch_to",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
