# Generated by Django 5.0.6 on 2026-08-06 11:10

import doctors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0005_doctorabsence"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="working_days",
            field=models.JSONField(default=doctors.models.default_working_days),
        ),
    ]
