# Generated by Django 5.0.6 on 2026-09-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0006_doctor_working_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="degree",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
