# Generated by Django 5.0.6 on 2026-10-02 07:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_doctor_degree'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='receptionists',
            field=models.ManyToManyField(blank=True, related_name='assigned_doctors', to=settings.AUTH_USER_MODEL),
        ),
    ]
